package com.miaclean.app.data.hash

import android.content.Context
import android.net.Uri
import io.mockk.mockk
import com.miaclean.app.data.hash.DummyMediaHarness
import io.mockk.every
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import java.io.ByteArrayInputStream

class Md5HasherIntegrationTest {

    private lateinit var context: Context
    private lateinit var contentResolver: android.content.ContentResolver
    private lateinit var hasher: Md5Hasher
    // Uri will be generated by DummyMediaHarness

    @Before
    fun setup() {
        context = mockk()
        contentResolver = mockk()
        every { context.contentResolver } returns contentResolver
        hasher = Md5Hasher(context)
    }

    @Test
    fun `hash dummy media matches known vector`() {
        // Known vector for "hello world"
        val input = "hello world".toByteArray()
        val expected = "5eb63bbbe01eeed093cb22bb8f5acdc3"
        // Create Uri from dummy bytes using helper
        val uri = DummyMediaHarness.uriFromBytes(context, input)
        // Mock resolver to return stream from these bytes
        every { contentResolver.openInputStream(uri) } returns ByteArrayInputStream(input)
        val result = hasher.hash(uri)
        assertEquals(expected, result)
    }
}
